management:
  security:
    enabled: false

server:
  port: 8889

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///home/darek/Devel/Workspace/Spring/spring-io-lab8-config
