management:
  security:
    enabled: false

server:
  port: 8889

spring:
  application:
    name: configservice
  cloud:
    config:
      server:
        git:
          uri: file:///home/darek/Devel/Workspace/Spring/spring-io-lab8-config

eureka:
  client:
    service-url:
      defaultZone: ${eureka.peer:http://localhost:8765/eureka/}
